repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 8.0.1
        hooks:
        - id: isort
          additional_dependencies: [toml]
      - repo: https://github.com/python/black
        rev: 26.1.0
        hooks:
        - id: black
      - repo: https://github.com/pycqa/flake8
        rev: 7.3.0
        hooks:
        - id: flake8
      - repo: https://github.com/pycqa/pylint
        rev: v4.0.5
        hooks:
        - id: pylint
      - repo: https://github.com/codespell-project/codespell
        rev: v2.2.4
        hooks:
        - id: codespell
      - repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v22.1.4
        hooks:
        - id: clang-format
          files: \.(cu|cuh|h|cpp)$

