repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 5.12.0
        hooks:
        - id: isort
          additional_dependencies: [toml]
      - repo: https://github.com/python/black
        rev: 23.3.0
        hooks:
        - id: black
      - repo: https://github.com/pycqa/flake8
        rev: 6.0.0
        hooks:
        - id: flake8
      - repo: https://github.com/pycqa/pylint
        rev: v2.17.4
        hooks:
        - id: pylint
      - repo: https://github.com/codespell-project/codespell
        rev: v2.2.4
        hooks:
        - id: codespell
      - repo: local
        hooks:
        - id: clang-format
          name: clang-format
          description: Format files with ClangFormat.
          entry: clang-format --dry-run --Werror
          language: system 
          files: \.(cu|cuh|h|cpp)$

