build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create --name implicit numpy scipy
  - activate implicit
  - pip install -r requirements.txt --ignore-installed flake8 isort cpplint nmslib
  - pip install -e .

test_script:
  - python setup.py test

